////////////////////////////////////////////////
// Dependencies
////////////////////////////////////////////////
const mongoose = require("./connection")
const Bookmark = require("./bookmark")

////////////////////////////////////////////////
// Seed
////////////////////////////////////////////////
const startBookmarks = [
    {
        name: "Google",
        url: "https://www.google.com/",
        slogan: "Don't Be Evil",
        description: "A search engine so ubiquitous that its very name has become a verb. Go ahead. Google it.",
    },
    {
        name: "YouTube",
        url: "https://www.youtube.com/",
        slogan: "Broadcast Yourself",
        description: "A video sharing platform where you can find anything from helpful tutorials to conspiracy nuts to grown adults making millions of dollars by recording themselves playing video games.",
    },
    {
        name: "Instagram",
        url: "https://www.instagram.com/",
        slogan: "Capture and Share the World's Moment",
        description: "A photo- & video-sharing social media platform that we all like to pretend isn't owned by Facebook.",
    },
    {
        name: "Twitter",
        url: "https://twitter.com/",
        slogan: "What's Happening",
        description: "A microblogging and social networking site, consisting of short 'tweets' generated by the user. Proof that brevity isnt ALWAYS the soul of wit.",
    },
    {
        name: "LinkedIn",
        url: "https://www.linkedin.com/",
        slogan: "Do Business Where Business Is Done",
        description: "A professional-oriented social networking and job-seeking site, sometimes described as 'Facebook for people with a 401k'.",
    },
    {
        name: "reddit",
        url: "https://www.reddit.com/",
        slogan: "The Front Page of the Internet",
        description: "A social news aggregating, web content rating, and discussion site. Somehow there's a subreddit for absolutely anything you can possibly think of.",
    }
]

mongoose.connection.on("open", () => {
    Bookmark.deleteMany({}, (err, data) => {
        Bookmark.create(startBookmarks, (err, data) => {
            console.log("==========BOOKMARKS ADDED==========")
            console.log(data)
            console.log("==========BOOKMARKS ADDED==========")
        })
    })
})